name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build disk space
      uses: easimon/maximize-build-disk-space@v1
      with:
        root-reserve-mb: 5120 # Reserve 5120MB on the root volume
        temp-reserve-mb: 5120 # Reserve 5120MB on the temporary volume
        overprovision-lvm: true # Use LVM overprovisioning if available
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_HUB_USERNAME }}/runpod-serverless:latest
        cache-from: type=gha # Use GitHub Actions cache
        cache-to: type=gha,mode=max # Store cache in GitHub Actions
